"""empty message

Revision ID: 02bc6e863676
Revises: ac50f295c37d
Create Date: 2017-04-15 16:47:00.547582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bc6e863676'
down_revision = 'ac50f295c37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # op.create_unique_constraint(None, 'client_status', ['color'])
    op.add_column('clients', sa.Column('estimated_completion', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'users', ['username'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('clients', 'estimated_completion')
    op.drop_constraint(None, 'client_status', type_='unique')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
