"""empty message

Revision ID: 10ada5cf6d71
Revises: d97853d946f9
Create Date: 2017-04-13 08:21:05.573518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ada5cf6d71'
down_revision = 'd97853d946f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=80), nullable=False),
    sa.Column('venueAddress', sa.String(), nullable=True),
    sa.Column('venueCity', sa.String(), nullable=True),
    sa.Column('venueState', sa.String(), nullable=True),
    sa.Column('venue_email', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_email'),
    sa.UniqueConstraint('venue_name')
    )
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('venues')
    # ### end Alembic commands ###
