"""empty message

Revision ID: 391d57959593
Revises: 5a923d35015b
Create Date: 2017-04-16 22:23:10.317697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391d57959593'
down_revision = '5a923d35015b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userData',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('games', sa.String(length=80), nullable=True),
    sa.Column('characters', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('userData')
    # ### end Alembic commands ###
