"""empty message

Revision ID: 5a923d35015b
Revises: e1669f5dc868
Create Date: 2017-04-16 22:17:04.004080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a923d35015b'
down_revision = 'e1669f5dc868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('facebookUrl', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # op.drop_table('sqlite_sequence')
    op.add_column('users', sa.Column('league', sa.String(), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'region')
    op.drop_column('users', 'region')
    op.drop_column('users', 'league')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('regions')
    op.drop_table('leagues')
    # ### end Alembic commands ###
