"""empty message

Revision ID: 5c4bf894ba90
Revises: 02bc6e863676
Create Date: 2017-04-15 16:56:01.793535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4bf894ba90'
down_revision = '02bc6e863676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    op.add_column('client_status', sa.Column('text_color', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'client_status', ['text_color'])
    # op.create_unique_constraint(None, 'client_status', ['color'])
    # op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'client_status', type_='unique')
    op.drop_constraint(None, 'client_status', type_='unique')
    op.drop_column('client_status', 'text_color')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
