"""empty message

Revision ID: 8a21f2f29721
Revises: 
Create Date: 2017-04-18 23:03:31.272422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a21f2f29721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    op.drop_table('Locations')
    op.add_column('matchLog', sa.Column('game', sa.String(), nullable=True))
    op.add_column('matchLog', sa.Column('league', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'users', ['username'])
    # op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('matchLog', 'league')
    op.drop_column('matchLog', 'game')
    op.create_table('Locations',
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('Name', sa.NullType(), nullable=True),
    sa.Column('Address', sa.NullType(), nullable=True),
    sa.Column('City', sa.NullType(), nullable=True),
    sa.Column('State', sa.NullType(), nullable=True),
    sa.Column('Country', sa.NullType(), nullable=True),
    sa.Column('Lat', sa.NullType(), nullable=True),
    sa.Column('Lon', sa.NullType(), nullable=True),
    sa.Column('url', sa.NullType(), nullable=True),
    sa.Column('info', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
