"""empty message

Revision ID: e1669f5dc868
Revises: 
Create Date: 2017-04-16 21:28:11.294180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1669f5dc868'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1', sa.String(), nullable=True),
    sa.Column('p2', sa.String(), nullable=True),
    sa.Column('char1', sa.String(), nullable=True),
    sa.Column('char2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('matchLog')
    op.drop_table('game')
    op.drop_table('characters')
    # ### end Alembic commands ###
